### ISSUE TITLE
infra-operator-controller-manager CrashLoopBackOff panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Loumy** [openstack-k8s-operators/infra-operator#200]
in openstack-operator the infra-operator-controller-manager crash when baremetal deploy start

```
2024-03-12T18:22:03Z    INFO    Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference        {"controller": "ipset", "controllerGroup": "network.openstack.org", "controllerKind": "IPSet", "IPSet": {"name":"edpm-compute-01","namespace":"openstack"}, "namespace": "openstack", "name": "edpm-compute-01", "reconcileID": "5d768fc0-07ab-445a-ad16-22597016b542"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17d32a9]

goroutine 331 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.5/pkg/internal/controller/controller.go:116 +0x1fa
panic({0x19ccdc0, 0x2b8ea00})
        /usr/lib/golang/src/runtime/panic.go:884 +0x213
github.com/openstack-k8s-operators/infra-operator/controllers/network.(*IPSetReconciler).ensureReservation(0xc00030dd10, {0x1eb4410, 0xc002a30240}, 0xc002a0c2c0, 0xc0028ff7c0, 0xc00050c2c0, 0xc000479ab0)
        /remote-source/controllers/network/ipset_controller.go:441 +0x949
github.com/openstack-k8s-operators/infra-operator/controllers/network.(*IPSetReconciler).reconcileNormal(0xc00030dd10, {0x1eb4410, 0xc002a30240}, 0xc002a0c2c0, 0xc002a0c2c0?)
        /remote-source/controllers/network/ipset_controller.go:254 +0x2a9
github.com/openstack-k8s-operators/infra-operator/controllers/network.(*IPSetReconciler).Reconcile(0xc00030dd10, {0x1eb4410, 0xc002a30240}, {{{0xc000c108f6?, 0x5?}, {0xc000c10900?, 0xc000e5fd48?}}})
        /remote-source/controllers/network/ipset_controller.go:147 +0x64f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1eb6a80?, {0x1eb4410?, 0xc002a30240?}, {{{0xc000c108f6?, 0xb?}, {0xc000c10900?, 0x0?}}})
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.5/pkg/internal/controller/controller.go:119 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0003fea00, {0x1eb4368, 0xc0001faa50}, {0x1a784e0?, 0xc0006402c0?})
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.5/pkg/internal/controller/controller.go:316 +0x3ca
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0003fea00, {0x1eb4368, 0xc0001faa50})
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.5/pkg/internal/controller/controller.go:266 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.5/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.5/pkg/internal/controller/controller.go:223 +0x587
```

IPset
```
oc get ipset edpm-compute-01 -o yaml
apiVersion: network.openstack.org/v1beta1
kind: IPSet
metadata:
  creationTimestamp: "2024-03-12T18:20:24Z"
  finalizers:
  - IPSet
  generation: 1
  name: edpm-compute-01
  namespace: openstack
  ownerReferences:
  - apiVersion: dataplane.openstack.org/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: OpenStackDataPlaneNodeSet
    name: openstack-edpm-ipam
    uid: b3a9ac56-ca72-42d5-9307-975e63b5add1
  resourceVersion: "19506379"
  uid: 2d02c16d-c3a0-47ef-8d0e-fa10cc998b2b
spec:
  immutable: false
  networks:
  - defaultRoute: true
    name: CtlPlane
    subnetName: subnet1
  - name: InternalApi
    subnetName: subnet1
  - name: Storage
    subnetName: subnet1
  - name: Tenant
    subnetName: subnet1
  - name: StorageMgmt
    subnetName: subnet1
status:
  conditions:
  - lastTransitionTime: "2024-03-12T18:20:43Z"
    message: Setup started
    reason: Init
    status: Unknown
    type: Ready
  - lastTransitionTime: "2024-03-12T18:20:24Z"
    message: Input data complete
    reason: Ready
    status: "True"
    type: InputReady
  - lastTransitionTime: "2024-03-12T18:20:24Z"
    message: Reservation create not started
    reason: Init
    status: Unknown
    type: ReservationReady
```

Reserveration 
```
apiVersion: network.openstack.org/v1beta1
kind: Reservation
metadata:
  creationTimestamp: "2024-03-12T18:20:24Z"
  finalizers:
  - IPSet
  generation: 1
  labels:
    ipam.network.openstack.org/CtlPlane: subnet1
  name: edpm-compute-01
  namespace: openstack
  ownerReferences:
  - apiVersion: network.openstack.org/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: IPSet
    name: edpm-compute-01
    uid: 2d02c16d-c3a0-47ef-8d0e-fa10cc998b2b
  resourceVersion: "19505890"
  uid: a0b1b05a-6040-4933-83ce-e5c51888b873
spec:
  ipSetRef:
    name: edpm-compute-01
    namespace: openstack
    uid: 2d02c16d-c3a0-47ef-8d0e-fa10cc998b2b
  reservation:
    CtlPlane:
      address: 192.168.122.100
      network: CtlPlane
      subnet: subnet1
```

**Comment by clopnis** [comment]
This issue is coming from  ` - defaultRoute: true` set in ipset but not default route in netconfig
